export { Color } from "@tiptap/extension-color";
export { Dropcursor } from "@tiptap/extension-dropcursor";
export { FontFamily } from "@tiptap/extension-font-family";
export { StarterKit } from "@tiptap/starter-kit";
export { TableOfContents } from "@tiptap-pro/extension-table-of-contents";
export { TextAlign } from "@tiptap/extension-text-align";
export { TextStyle } from "@tiptap/extension-text-style";
export { Typography } from "@tiptap/extension-typography";
export { Underline } from "@tiptap/extension-underline";
export { Document } from "./Document";
export { FontSize } from "./FontSize";
export { Heading } from "./Heading";
export { Button } from "./Button";
// export { Columns, Column } from "./MultiColumn";
