export const timezoneStandardAbbreviationMap: Record<string, string> = {
  // North America
  "America/New_York": "EST",
  "America/Chicago": "CST",
  "America/Denver": "MST",
  "America/Los_Angeles": "PST",
  "America/Phoenix": "MST",
  "America/Anchorage": "AKST",
  "America/Adak": "HST",
  "Pacific/Honolulu": "HST",

  // South America
  "America/Sao_Paulo": "BRT",
  "America/Argentina/Buenos_Aires": "ART",
  "America/Caracas": "VET",
  "America/Bogota": "COT",
  "America/Lima": "PET",
  "America/La_Paz": "BOT",
  "America/Santiago": "CLT",
  "America/Montevideo": "UYT",

  // Europe
  "Europe/London": "GMT",
  "Europe/Dublin": "GMT",
  "Europe/Paris": "CET",
  "Europe/Berlin": "CET",
  "Europe/Madrid": "CET",
  "Europe/Rome": "CET",
  "Europe/Amsterdam": "CET",
  "Europe/Brussels": "CET",
  "Europe/Zurich": "CET",
  "Europe/Stockholm": "CET",
  "Europe/Oslo": "CET",
  "Europe/Vienna": "CET",
  "Europe/Prague": "CET",
  "Europe/Budapest": "CET",
  "Europe/Warsaw": "CET",
  "Europe/Helsinki": "EET",
  "Europe/Athens": "EET",
  "Europe/Istanbul": "TRT",
  "Europe/Moscow": "MSK",

  // Africa
  "Africa/Cairo": "EET",
  "Africa/Johannesburg": "SAST",
  "Africa/Nairobi": "EAT",
  "Africa/Lagos": "WAT",
  "Africa/Algiers": "CET",
  "Africa/Casablanca": "WET",
  "Africa/Accra": "GMT",

  // Asia
  "Asia/Tokyo": "JST",
  "Asia/Shanghai": "CST",
  "Asia/Hong_Kong": "HKT",
  "Asia/Singapore": "SGT",
  "Asia/Seoul": "KST",
  "Asia/Kolkata": "IST",
  "Asia/Bangkok": "ICT",
  "Asia/Jakarta": "WIB",
  "Asia/Dubai": "GST",
  "Asia/Karachi": "PKT",
  "Asia/Tehran": "IRST",
  "Asia/Jerusalem": "IST",
  "Asia/Baghdad": "AST",
  "Asia/Kabul": "AFT",
  "Asia/Yekaterinburg": "YEKT",
  "Asia/Novosibirsk": "NOVT",
  "Asia/Vladivostok": "VLAT",
  "Asia/Magadan": "MAGT",
  "Asia/Kamchatka": "PETT",

  // Australia & Oceania
  "Australia/Sydney": "AEST",
  "Australia/Melbourne": "AEST",
  "Australia/Brisbane": "AEST",
  "Australia/Adelaide": "ACST",
  "Australia/Darwin": "ACST",
  "Australia/Perth": "AWST",
  "Pacific/Auckland": "NZST",
  "Pacific/Fiji": "FJT",
  "Pacific/Guam": "ChST",
  "Pacific/Port_Moresby": "PGT",
  "Pacific/Tongatapu": "TOT",
  "Pacific/Apia": "WSST",
  "Pacific/Noumea": "NCT",
  "Pacific/Majuro": "MHT",
  "Pacific/Tarawa": "GILT",
  "Pacific/Pago_Pago": "SST",

  // Antarctica
  "Antarctica/Casey": "AWST",
  "Antarctica/Davis": "DAVT",
  "Antarctica/DumontDUrville": "DDUT",
  "Antarctica/Macquarie": "MIST",
  "Antarctica/Mawson": "MAWT",
  "Antarctica/Palmer": "CLT",
  "Antarctica/Rothera": "ROTT",
  "Antarctica/Syowa": "SYOT",
  "Antarctica/Troll": "UTC+2",
  "Antarctica/Vostok": "VOST",

  // Others
  "Etc/UTC": "UTC",
  "Etc/GMT": "GMT",
  "Etc/GMT+1": "GMT+1",
  "Etc/GMT-1": "GMT-1",
  "Etc/GMT+12": "GMT+12",
  "Etc/GMT-12": "GMT-12",
};

export const timezoneDaylightAbbreviationMap: Record<string, string> = {
  // North America
  "America/New_York": "EDT",
  "America/Chicago": "CDT",
  "America/Denver": "MDT",
  "America/Los_Angeles": "PDT",
  "America/Phoenix": "MST",
  "America/Anchorage": "AKDT",
  "America/Adak": "HDT",
  "Pacific/Honolulu": "HST",

  // South America
  "America/Sao_Paulo": "BRST",
  "America/Argentina/Buenos_Aires": "ARST",
  "America/Caracas": "VET",
  "America/Bogota": "COT",
  "America/Lima": "PET",
  "America/La_Paz": "BOT",
  "America/Santiago": "CLST",
  "America/Montevideo": "UYST",

  // Europe
  "Europe/London": "BST",
  "Europe/Dublin": "IST",
  "Europe/Paris": "CEST",
  "Europe/Berlin": "CEST",
  "Europe/Madrid": "CEST",
  "Europe/Rome": "CEST",
  "Europe/Amsterdam": "CEST",
  "Europe/Brussels": "CEST",
  "Europe/Zurich": "CEST",
  "Europe/Stockholm": "CEST",
  "Europe/Oslo": "CEST",
  "Europe/Vienna": "CEST",
  "Europe/Prague": "CEST",
  "Europe/Budapest": "CEST",
  "Europe/Warsaw": "CEST",
  "Europe/Helsinki": "EEST",
  "Europe/Athens": "EEST",
  "Europe/Istanbul": "TRT",
  "Europe/Moscow": "MSK",

  // Africa
  "Africa/Cairo": "EEST",
  "Africa/Johannesburg": "SAST",
  "Africa/Nairobi": "EAT",
  "Africa/Lagos": "WAT",
  "Africa/Algiers": "CET",
  "Africa/Casablanca": "WEST",
  "Africa/Accra": "GMT",

  // Asia
  "Asia/Tokyo": "JST",
  "Asia/Shanghai": "CST",
  "Asia/Hong_Kong": "HKT",
  "Asia/Singapore": "SGT",
  "Asia/Seoul": "KST",
  "Asia/Kolkata": "IST",
  "Asia/Bangkok": "ICT",
  "Asia/Jakarta": "WIB",
  "Asia/Dubai": "GST",
  "Asia/Karachi": "PKT",
  "Asia/Tehran": "IRDT",
  "Asia/Jerusalem": "IDT",
  "Asia/Baghdad": "AST",
  "Asia/Kabul": "AFT",
  "Asia/Yekaterinburg": "YEKT",
  "Asia/Novosibirsk": "NOVT",
  "Asia/Vladivostok": "VLAT",
  "Asia/Magadan": "MAGT",
  "Asia/Kamchatka": "PETT",

  // Australia & Oceania
  "Australia/Sydney": "AEDT",
  "Australia/Melbourne": "AEDT",
  "Australia/Brisbane": "AEST",
  "Australia/Adelaide": "ACDT",
  "Australia/Darwin": "ACST",
  "Australia/Perth": "AWST",
  "Pacific/Auckland": "NZDT",
  "Pacific/Fiji": "FJST",
  "Pacific/Guam": "ChST",
  "Pacific/Port_Moresby": "PGT",
  "Pacific/Tongatapu": "TOT",
  "Pacific/Apia": "WSDT",
  "Pacific/Noumea": "NCST",
  "Pacific/Majuro": "MHT",
  "Pacific/Tarawa": "GILT",
  "Pacific/Pago_Pago": "SST",

  // Antarctica
  "Antarctica/Casey": "AWST",
  "Antarctica/Davis": "DAVT",
  "Antarctica/DumontDUrville": "DDUT",
  "Antarctica/Macquarie": "MIST",
  "Antarctica/Mawson": "MAWT",
  "Antarctica/Palmer": "CLST",
  "Antarctica/Rothera": "ROTT",
  "Antarctica/Syowa": "SYOT",
  "Antarctica/Troll": "CEST",
  "Antarctica/Vostok": "VOST",

  // Others
  "Etc/UTC": "UTC",
  "Etc/GMT": "GMT",
  "Etc/GMT+1": "GMT+1",
  "Etc/GMT-1": "GMT-1",
  "Etc/GMT+12": "GMT+12",
  "Etc/GMT-12": "GMT-12",
};
